# 安全设置
loginTimeout: 120
maxAccountsPerIP: 2

# 位置设置
initialJoinLocation:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

defaultSpawnLocation:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0