# XpcMCLogin Configuration

language: en

features:
  force_login: false

  custom_initial_location:
    enabled: false
    location:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0

  custom_spawn_location:
    enabled: false
    location:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0