name: XpcMCLogin
version: 1.0.0
main: xyz.xpcmc.login.XpcMCLogin
api-version: 1.20
commands:
  l:
    description: Login command
    usage: /l <password>
  reg:
    description: Register command
    usage: /reg <password> <confirm password>
  l-to:
    description: Force login for another player
    usage: /l-to <player>
permissions:
  xpcmclogin.admin:
    description: Admin permissions for XpcMCLogin
    default: op